# Appendix 3: Python Libraries Crash Course

## Part 2: Multi-Dimensional Numpy Arrays

### Nested Lists

In [1]:
project_1 = [-200, 20, 50, 70, 100, 50]
project_2 = [-50, 10, 25, 25, 50]
project_3 = [-1000, 200, 200, 300, 500, 500, 750, 250]

In [2]:
all_proj = [project_1, project_2, project_3]

In [3]:
all_proj

[[-200, 20, 50, 70, 100, 50],
 [-50, 10, 25, 25, 50],
 [-1000, 200, 200, 300, 500, 500, 750, 250]]

In [4]:
type(all_proj)

list

In [5]:
len(all_proj)

3

In [6]:
all_proj[0]

[-200, 20, 50, 70, 100, 50]

In [7]:
all_proj[2]

[-1000, 200, 200, 300, 500, 500, 750, 250]

In [8]:
all_proj[-1]

[-1000, 200, 200, 300, 500, 500, 750, 250]

In [9]:
all_proj[:2]

[[-200, 20, 50, 70, 100, 50], [-50, 10, 25, 25, 50]]

In [10]:
all_proj[-2:]

[[-50, 10, 25, 25, 50], [-1000, 200, 200, 300, 500, 500, 750, 250]]

In [11]:
all_proj[0][0]

-200

In [12]:
all_proj[:][0]

[-200, 20, 50, 70, 100, 50]

In [15]:
I0 = []
for proj in all_proj:
    I0.append(proj[0])

In [16]:
I0

[-200, -50, -1000]

### 2-dim Numpy Arrays

In [1]:
import numpy as np

In [2]:
cf1 = [-200, 20, 50, 70, 100, 50]
cf2 = [-150, 25, 60, 50, 50, 40]
cf3 = [-250, 10, 25, 50, 125, 200]
nl = [cf1, cf2, cf3]

In [3]:
nl

[[-200, 20, 50, 70, 100, 50],
 [-150, 25, 60, 50, 50, 40],
 [-250, 10, 25, 50, 125, 200]]

In [4]:
np.array(nl)

array([[-200,   20,   50,   70,  100,   50],
       [-150,   25,   60,   50,   50,   40],
       [-250,   10,   25,   50,  125,  200]])

In [5]:
cfs = np.array(nl)

In [6]:
cfs

array([[-200,   20,   50,   70,  100,   50],
       [-150,   25,   60,   50,   50,   40],
       [-250,   10,   25,   50,  125,  200]])

In [7]:
type(cfs)

numpy.ndarray

In [8]:
cfs.shape# 리스트 안에 리스트를 구성한 것을 2차원 배열이라고 한다.

(3, 6)

In [9]:
cfs[0]

array([-200,   20,   50,   70,  100,   50])

In [10]:
cfs[-1]

array([-250,   10,   25,   50,  125,  200])

In [11]:
cfs[1:]

array([[-150,   25,   60,   50,   50,   40],
       [-250,   10,   25,   50,  125,  200]])

In [12]:
cfs[0][0]

-200

In [13]:
cfs[0, 0] ## 행렬 속성처럼 바로 접근도 가능하다는 장점이 있다.

-200

### Slicing 2-dim Numpy Arrays (Part 1)

In [14]:
import numpy as np

In [15]:
cf1 = [-200, 20, 50, 70, 100, 50]
cf2 = [-150, 25, 60, 50, 50, 40]
cf3 = [-250, 10, 25, 50, 125, 200]

In [16]:
cfs = np.array([cf1, cf2, cf3])
cfs

array([[-200,   20,   50,   70,  100,   50],
       [-150,   25,   60,   50,   50,   40],
       [-250,   10,   25,   50,  125,  200]])

In [17]:
cfs.shape

(3, 6)

In [18]:
cfs[:, 0]# , 를 찍는 건 모든 행에 대해서 적용하는 것이다. cfs[:,0]자세하게 보면 모든 행 [:]에 대한 인덱스 0의 값 이라는 요약이다.
# 항상 생각하자, 행 슬라이싱 열 슬라이싱 이렇게..

array([-200, -150, -250])

In [37]:
cfs[:, -1]

array([ 50,  40, 200])

In [38]:
cfs[:, :2]# 해석 : 모든 행에 대해서, 0, 1값을 배열로 리턴해라. 모든행 [:], [:2]값 가져오기. 라고 생각하면 명쾌하다.

array([[-200,   20],
       [-150,   25],
       [-250,   10]])

In [40]:
cfs[2, 1:]

array([ 10,  25,  50, 125, 200])

In [41]:
cfs[-2:, :2]

array([[-150,   25],
       [-250,   10]])

In [42]:
project_1 = [-200, 20, 50, 70, 100, 50]
project_2 = [-50, 10, 25, 25, 50]
project_3 = [-1000, 200, 200, 300, 500, 500, 750, 250]

In [48]:
array = np.array([project_1, project_2, project_3]) ## 차원이 맞지 않는 데이터 형이다. 

/var/folders/gj/jnywjty93y99mk904fhg73br0000gn/T/ipykernel_1512/3021070066.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array = np.array([project_1, project_2, project_3]) ## 차원이 맞지 않는 데이터 형이다.


In [49]:
array

array([list([-200, 20, 50, 70, 100, 50]), list([-50, 10, 25, 25, 50]),
       list([-1000, 200, 200, 300, 500, 500, 750, 250])], dtype=object)

In [50]:
array.shape ## 이건 그냥 1차원 형으로 형성된다.

(3,)

In [51]:
# array[:, 0]

In [52]:
project_1 = np.array([-200, 20, 50, 70, 100, 50, 0, 0])
project_2 = np.array([-50, 10, 25, 25, 50, 0, 0, 0])
project_3 = np.array([-1000, 200, 200, 300, 500, 500, 750, 250])

In [53]:
projects = np.array([project_1, project_2, project_3])

In [54]:
projects

array([[ -200,    20,    50,    70,   100,    50,     0,     0],
       [  -50,    10,    25,    25,    50,     0,     0,     0],
       [-1000,   200,   200,   300,   500,   500,   750,   250]])

In [57]:
projects.shape

(3, 8)

In [58]:
projects[:, 0]

array([ -200,   -50, -1000])

In [59]:
project_1 = np.array([-200, 20, 50, 70, 100, 50])

In [60]:
project_1.resize(8) # 배열의 크기를 8로 조정하고, 기본값으로 0를 넣을 수 있다.

In [61]:
project_1

array([-200,   20,   50,   70,  100,   50,    0,    0])

### Slicing 2-dim Numpy Arrays (Part 2)

In [ ]:
import numpy as np

In [62]:
cf1 = np.array([-200, 20, 50, 70, 100, 50])
cf2 = np.array([-150, 25, 60, 50, 50, 40])
cf3 = np.array([-250, 10, 25, 50, 125, 200])

In [63]:
cfs = np.array([cf1, cf2, cf3])
cfs

array([[-200,   20,   50,   70,  100,   50],
       [-150,   25,   60,   50,   50,   40],
       [-250,   10,   25,   50,  125,  200]])

In [64]:
cf1[[0, 3, -1]] ## 인덱스 포지션으로 넘길 수 있으며, 다만 [] 기본 넘파이 배열을 위한 브라켓을 열어주어야 한다. 

array([-200,   70,   50])

In [66]:
cfs[[0,-1], 0] ## 넘파이 차원 배열에 대해서, 앞에서 행을 선택하고, 뒤에서 인덱스를 넘겨줄 수 있따.

array([-200, -250])

In [67]:
cfs[0, [0, 2, -1]] # 첫 행의 데이터 배열에서 0, 2, -1 인덱스 값으로 배열을 리턴해라.

array([-200,   50,   50])

### Recap: Changing Elements in a Numpy Array / slice

In [68]:
import numpy as np

In [69]:
cf1 = [-200, 20, 50, 70, 100, 50]
cf2 = [-150, 25, 60, 50, 50, 40]
cf3 = [-250, 10, 25, 50, 125, 200]

In [70]:
cfs = np.array([cf1, cf2, cf3])
cfs

array([[-200,   20,   50,   70,  100,   50],
       [-150,   25,   60,   50,   50,   40],
       [-250,   10,   25,   50,  125,  200]])

In [71]:
cfs[:, 0] = -200

In [72]:
cfs

array([[-200,   20,   50,   70,  100,   50],
       [-200,   25,   60,   50,   50,   40],
       [-200,   10,   25,   50,  125,  200]])

In [76]:
cfs[:, 0] = cfs[:, 0] - 10

In [77]:
cfs

array([[-230,   20,   50,   70,  100,   50],
       [-230,   25,   60,   50,   50,   40],
       [-230,   10,   25,   50,  125,  200]])

In [78]:
cfs[:, 0] = [-200, -150, -250]

In [79]:
cfs

array([[-200,   20,   50,   70,  100,   50],
       [-150,   25,   60,   50,   50,   40],
       [-250,   10,   25,   50,  125,  200]])

In [80]:
I0s = cfs[:, 0]
I0s

array([-200, -150, -250])

In [81]:
I0s[0] = -180
I0s

array([-180, -150, -250])

In [82]:
cfs

array([[-180,   20,   50,   70,  100,   50],
       [-150,   25,   60,   50,   50,   40],
       [-250,   10,   25,   50,  125,  200]])

In [83]:
cf5 = cfs[:, -1].copy() ## 카피 메서드를 통해서 값을 복사하고 만지면 데이터에 변화가 없다.
cf5

array([ 50,  40, 200])

In [84]:
cf5[-1] = 150
cf5

array([ 50,  40, 150])

In [85]:
cfs

array([[-180,   20,   50,   70,  100,   50],
       [-150,   25,   60,   50,   50,   40],
       [-250,   10,   25,   50,  125,  200]])

### Row- and Column wise operations

In [20]:
import numpy as np
np.set_printoptions(precision=2, suppress= True) # 2차원 배열 생성

In [21]:
project_1 = [-200, 20, 50, 70, 100, 50, 0, 0]
project_2 = [-50, 10, 25, 25, 50, 0, 0, 0]
project_3 = [-1000, 200, 200, 300, 500, 500, 750, 250]

In [22]:
projects = np.array([project_1, project_2, project_3]) 

In [23]:
projects

array([[ -200,    20,    50,    70,   100,    50,     0,     0],
       [  -50,    10,    25,    25,    50,     0,     0,     0],
       [-1000,   200,   200,   300,   500,   500,   750,   250]])

In [24]:
np.sum(projects) ## 그냥 모든 것들을 더한 값이 나온다. 하지만 의미가 없다.

1850

In [25]:
np.sum(projects, axis = 0) # axis가 0이면 각 열별로 합을 뱉는다.

array([-1250,   230,   275,   395,   650,   550,   750,   250])

In [26]:
np.sum(projects, axis = 1) # 각 행의 합을 뱉는다.

array([  90,   60, 1700])

In [27]:
np.cumsum(projects, axis = 1) # 각 행의 누적합을 뱉는다.

array([[ -200,  -180,  -130,   -60,    40,    90,    90,    90],
       [  -50,   -40,   -15,    10,    60,    60,    60,    60],
       [-1000,  -800,  -600,  -300,   200,   700,  1450,  1700]])

In [28]:
np.mean(projects, axis = 1) # 각 행의 평균을 뱉는다.

array([ 11.25,   7.5 , 212.5 ])

In [29]:
np.mean(projects, axis = 0) # 각 열의 평균

array([-416.67,   76.67,   91.67,  131.67,  216.67,  183.33,  250.  ,
         83.33])

In [30]:
np.mean(projects) # 그냥 전체 수에 대한 평균

77.08333333333333