# NumPy 한번에 제대로 배우기



---



## NumPy 특징

* Numerical Python의 약자
* 고성능 과학 계산용 패키지로 강력한 N차원 배열 객체
* 범용적 데이터 처리에 사용 가능한 다차원 컨테이너
* 정교한 브로드캐스팅(broadcasting) 기능
* 파이썬의 자료형 list와 비슷하지만, 더 빠르고 메모리를 효율적으로 관리
* 반복문 없이 데이터 배열에 대한 처리를 지원하여 빠르고 편리
* 데이터 과학 도구에 대한 생태계의 핵심을 이루고 있음

In [ ]:
import numpy as np



---



## 배열 생성

### 리스트로 배열 만들기


In [ ]:
a1 = np.array([1, 2, 3])
print(a1)
print(type(a1))
print(a1.shape)# 디멘션을 보여준다. 3개의 엘리먼트가 있으며, 쉼표 뒤에는 아무것도 없으므로 1차원 배열임을 안다.
print(a1[0], a1[1], a1[2]) # 개별로도 접근이 가능하다.
a1[0] = 4 # 지정한 곳에 값 수정도 가능하다.
print(a1)

[1 2 3]
<class 'numpy.ndarray'>
(3,)
1 2 3
[4 2 3]


In [ ]:
a2 = np.array([[1, 2], [3, 4]]) # 2차원 배열을 생성함
print(a2.shape)
print(a2)
print(a2[1, 1], a2[0, 0]) # 다음처럼 각 요소에 접근이 가능

(2, 2)
[[1 2]
 [3 4]]
4 1


In [ ]:
a3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
               [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
               [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]) # 3차원 배열 생성
print(a3.shape)
print(a3)

(3, 3, 3)
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


### 배열 생성 및 초기화

* `zeros()`: 모든 요소를 0으로 초기화

In [ ]:
print(np.zeros(10))
print(np.zeros((3, 3), dtype="uint8"))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


* `ones()`: 모든 요소를 1로 초기화

In [ ]:
print(np.ones(10))
print(np.ones((3, 3, 3), dtype="uint8"))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


* `full()`: 모든 요소를 지정한 값으로 초기화

In [ ]:
np.full((3, 3), 1.23)
# full은 내가 원하는 값으로 이루어진 배열을 구성할 수 있다.

array([[1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23]])

* `eye()`: 단위행렬(identity matrix) 생성
  + 주대각선의 원소가 모두 1이고 나머지 원소는 모두 0인 정사각 행렬

In [ ]:
np.eye(5)
# 단위행렬을 생성해주고,사이즈만 알려주면 알아서 생성이 된다.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

* `tri()`: 삼각행렬 생성

In [ ]:
np.tri(5)
# 크기만 주면 삼각행렬을 생성해준다.

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

* `empty()`: 초기화되지 않은 배열 생성
  + 초기화가 없어서 배열 생성비용 저렴하고 빠름
  + 초기화되지 않아서 기존 메모리 위치에 존재하는 값이 있음

In [ ]:
np.empty(10)
# 얘는 그냥 초기화없이 메모리에 저장된 랜덤한 데이터를 넣는다. 중요하진 않을 듯

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

* `_like()`: 지정된 배열과 shape가 같은 행렬 생성
  + `np.zeros_like()`
  + `np.ones_like()`
  + `np.full_like()`
  + `np.empty_like()`

In [ ]:
print(a1)
np.zeros_like(a1)
# a1의 shape를 가진 0으로 이루어진 배열을 만들어줘

[4 2 3]


array([0, 0, 0])

In [ ]:
print(a2)
np.ones_like(a2)

[[1 2]
 [3 4]]


array([[1, 1],
       [1, 1]])

In [ ]:
print(a3)
np.full_like(a3, 10)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

### 생성한 값으로 배열 생성

* `arange()`: 정수 범위로 배열 생성

In [ ]:
np.arange(0, 6, 2)
# 넘파이 배열을 생성하는 레인지 펑션과 비슷하다.

array([0, 2, 4])

* `linspace()`: 범위 내에서 균등 간격의 배열 생성

In [ ]:
np.linspace(0, 1, 100)
# 0부터 1까지 100개의 스탭을 만들어줘 라는 의미.

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

* `logspace()`: 범위 내에서 균등간격으로 로그 스케일로 배열 생성

In [ ]:
np.logspace(0, 1, 100)
# 이는 로그 단위에 따라서 100개의 스텝을 만들어 준다.

array([ 1.        ,  1.02353102,  1.04761575,  1.07226722,  1.09749877,
        1.12332403,  1.149757  ,  1.17681195,  1.20450354,  1.23284674,
        1.26185688,  1.29154967,  1.32194115,  1.35304777,  1.38488637,
        1.41747416,  1.45082878,  1.48496826,  1.51991108,  1.55567614,
        1.59228279,  1.62975083,  1.66810054,  1.70735265,  1.7475284 ,
        1.78864953,  1.83073828,  1.87381742,  1.91791026,  1.96304065,
        2.009233  ,  2.05651231,  2.10490414,  2.15443469,  2.20513074,
        2.25701972,  2.3101297 ,  2.36448941,  2.42012826,  2.47707636,
        2.53536449,  2.59502421,  2.65608778,  2.71858824,  2.7825594 ,
        2.84803587,  2.91505306,  2.98364724,  3.05385551,  3.12571585,
        3.19926714,  3.27454916,  3.35160265,  3.43046929,  3.51119173,
        3.59381366,  3.67837977,  3.76493581,  3.85352859,  3.94420606,
        4.03701726,  4.1320124 ,  4.22924287,  4.32876128,  4.43062146,
        4.53487851,  4.64158883,  4.75081016,  4.86260158,  4.97

### 랜덤값으로 배열 생성


* `random.random()`: 랜덤한 수의 배열 생성

In [ ]:
print(np.random.random(10))
# 0과 1사이의 랜덤한 10개로 이루어진 1차원 배열을 생성한다.
print(np.random.random((3, 3)))
# 차원을 만들어 생성도 가능

[0.44042271 0.99372423 0.21113029 0.97802528 0.34993879 0.4374802
 0.46658493 0.78139627 0.5563855  0.8023215 ]
[[0.26259197 0.86589022 0.44873179]
 [0.59161552 0.51327751 0.34226852]
 [0.91487766 0.31100848 0.7337231 ]]


* `random.randint()`: 일정 구간의 랜덤 정수의 배열 생성

In [ ]:
np.random.randint(0, 10, (3, 3))
# 0부터 10까지의 랜덤한 숫자로 이루어진 3*3행렬 생성

array([[6, 4, 6],
       [4, 2, 3],
       [7, 3, 9]])

* `random.normal()`: 정규분포(normal distribution)를 고려한 랜덤한 수의 배열 생성
* 평균=0, 표준편차=1, 3 x 3 배열

In [ ]:
np.random.normal(0, 1, size=(3, 3))

array([[ 1.52319709,  0.02086453, -1.00630363],
       [-1.57646102,  0.39000078,  1.32621929],
       [ 2.15038103,  0.35908876, -0.00315039]])

* `random.rand()`: 균등분포(uniform distribution)를 고려한 랜덤한 수의 배열 생성

In [ ]:
np.random.rand(3, 3)

array([[0.48199462, 0.24905018, 0.19596853],
       [0.0712572 , 0.57919799, 0.47666235],
       [0.44454471, 0.75222046, 0.67880936]])

* `random.randn()`: 표준 정규 분포(standard normal distribution)를 고려한 랜덤한 수의 배열 생성

In [ ]:
np.random.randn(10, 10)

array([[-1.9963578 ,  2.06235981, -1.04891558, -0.37951665, -0.27962799,
        -1.55683838, -1.49599274,  1.06026261, -2.05894487, -0.1408149 ],
       [ 0.92322781, -0.03030922,  1.02436537, -0.82271662,  2.52086446,
         0.01539345, -2.21910547, -0.27154177,  0.70668175, -0.94016807],
       [ 0.01428548, -0.78077614,  0.84886926, -0.44907125, -1.25861982,
         1.59653634, -0.92067771, -0.50117171, -2.50498651, -0.5513944 ],
       [-1.12910932, -0.45889691, -0.4691677 ,  1.81889135, -0.66283712,
        -0.46789179,  1.41190506, -1.95687486, -0.87058933,  1.13696006],
       [-0.89849727,  0.04326969,  1.34945638, -1.10829453,  0.21605537,
        -0.59578701, -2.13713821,  1.16962208, -1.50187178,  0.63249263],
       [-2.042164  , -0.57394431,  0.95255794,  1.05587446, -0.64732559,
         1.34327619, -0.25017641, -0.43454644, -0.76251283,  0.93928872],
       [ 0.00564777,  0.60782732,  0.39583404, -1.05158124, -1.04247812,
         1.33959263, -1.27254833,  1.46809712

### 표준 데이터 타입

In [ ]:
np.zeros(20, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones((3, 3), dtype=bool) 
# 1은 True, 0는 False이다.

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
np.full((3, 3), 2.102, dtype=float)

array([[2.102, 2.102, 2.102],
       [2.102, 2.102, 2.102],
       [2.102, 2.102, 2.102]])

### 날짜/시간 배열 생성


In [ ]:
date = np.array('2020-01-01', dtype=np.datetime64) # 날짜를 의미하는 데이터 타입을 지정해준다.
date

array('2020-01-01', dtype='datetime64[D]')

In [ ]:
date + np.arange(12)

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12'],
      dtype='datetime64[D]')

In [ ]:
datetime = np.datetime64('2020-06-06 12:00')
datetime

numpy.datetime64('2020-06-06T12:00')

In [ ]:
datetime = np.datetime64('2020-05-01 12:00:02.34', 'ns') # 나노초까지 표현 가능하다.
datetime

numpy.datetime64('2020-05-01T12:00:02.340000000')



---



## 배열 조회

### 배열 속성 정보

In [ ]:
def array_info(array):
    print(array)
    print("ndim:", array.ndim)
    print("shape:", array.shape)
    print('dtype:', array.dtype)
    print('size:', array.size)
    print('itemsize:', array.itemsize)
    print('nbytes:', array.nbytes)
    print('strides:', array.strides)

In [ ]:
array_info(a1)

[4 2 3]
ndim: 1
shape: (3,)
dtype: int64
size: 3
itemsize: 8
nbytes: 24
strides: (8,)


In [ ]:
array_info(a2)

[[1 2]
 [3 4]]
ndim: 2
shape: (2, 2)
dtype: int64
size: 4
itemsize: 8
nbytes: 32
strides: (16, 8)


In [ ]:
array_info(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
ndim: 3
shape: (3, 3, 3)
dtype: int64
size: 27
itemsize: 8
nbytes: 216
strides: (72, 24, 8)


### 인덱싱(Indexing)

In [ ]:
print(a1)
print(a1[0])
print(a1[2])
print(a1[-1])

[4 2 3]
4
3
3


In [ ]:
print(a2)
print(a2[1, 1])
print(a2[1, 0])
print(a2[-1, 1])

[[1 2]
 [3 4]]
4
3
4


In [ ]:
print(a3)
print(a3[1, 2, 1])
print(a3[1, 1, 1])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
8
5


### 슬라이싱(Slicing)

* 슬라이싱 구문: `a[start:stop:step]`
* 기본값: start=0, stop=ndim, step=1

In [ ]:
print(a1)
print(a1[0:2])
print(a1[:1])
print(a1[::2])
print(a1[::-1])

[4 2 3]
[4 2]
[4]
[4 3]
[3 2 4]


In [ ]:
print(a2)
print(a2[1])
print(a2[1,:])
print(a2[:2, :2])
print(a2[1:, ::-1])
print(a2[::-1, ::-1])

[[1 2]
 [3 4]]
[3 4]
[3 4]
[[1 2]
 [3 4]]
[[4 3]]
[[4 3]
 [2 1]]


### 불리언 인덱싱(Boolean Indexing)

* 배열 각 요소의 선택 여부를 불리언(True or False)로 지정
* True 값인 인덱스의 값만 조회

In [ ]:
print(a1)
bi = [False, True, True]
print(a1[bi])
# True 위치에 대한 값들만 나온다.
bi = [True, False, True]
print(a1[bi])

[4 2 3]
[2 3]
[4 3]


In [ ]:
print(a2)
bi = np.random.randint(0, 2, (2, 2), dtype=bool)
print(bi)
print(a2[bi])

[[1 2]
 [3 4]]
[[False False]
 [False False]]
[]


### 팬시 인덱싱(Fancy Indedxing)

In [ ]:
print(a1)
print([a1[0], a1[1]])
index = [0, 1]
print(a1[index])
index = np.array([[0, 1], [1, 2]])
print(a1[index])
# 인덱스의 형태에 따라서 차원을 맞춰 리턴한다.

[4 2 3]
[4, 2]
[4 2]
[[4 2]
 [2 3]]


In [ ]:
print(a2)
row = np.array([0, 1])
col = np.array([1, 1])
print(a2[row, col])
print(a2[row, :])
print(a2[:, col])

[[1 2]
 [3 4]]
[2 4]
[[1 2]
 [3 4]]
[[2 2]
 [4 4]]




---



## 배열 값 삽입/수정/삭제/복사

### 배열 값 삽입

* `insert()`: 배열의 특정 위치에 값 삽입
* axis를 지정하지 않으면 1차원 배열로 변환
* 추가할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [ ]:
print(a1)
b1 = np.insert(a1, 0, 10)
print(b1)
print(a1)
# a1의 데이터의 0번째 인덱스에 10을 넣어줘, 원본 배열은 변경되지 않는다.
c1 = np.insert(a1, 2, 10)
print(c1)

[4 2 3]
[10  4  2  3]
[4 2 3]
[ 4  2 10  3]


In [ ]:
print(a2)
b1 = np.insert(a2, 1, (2, 10), axis=0)
print(b1)
c1 = np.insert(a2, 1, (3, 7), axis=1)
print(c1)
# a2배열의 1번쨰 인덱스에 (2, 10)을 넣어줘, 행으로 넣어줘, axis=1이면 열로 넣어줘

[[1 2]
 [3 4]]
[[ 1  2]
 [ 2 10]
 [ 3  4]]
[[1 3 2]
 [3 7 4]]


### 배열 값 수정

* 배열의 인덱싱으로 접근하여 값 수정

In [ ]:
print(a1)
a1[0] = 7
a1[1] = 8
print(a1)
a1[:2] = 9
print(a1)

[4 2 3]
[7 8 3]
[9 9 3]


In [ ]:
print(a2)
a2[0, 1] = 10
a2[1, 1] = 21
print(a2)
a2[:2, :] = 1
print(a2)
row = np.array([0, 1])
col = np.array([1, 1])
a2[row, col] = 0
print(a2)

[[1 2]
 [3 4]]
[[ 1 10]
 [ 3 21]]
[[1 1]
 [1 1]]
[[1 0]
 [1 0]]


### 배열 값 삭제

* `delete()`: 배열의 특정 위치에 값 삭제
* axis를 지정하지 않으면 1차원 배열로 변환
* 삭제할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [ ]:
print(a1)
b1 = np.delete(a1, 1)
print(b1)
print(a1)
# 원본배열은 변하지 않았다, 인덱스 값이 삭제되어있다.

[9 9 3]
[9 3]
[9 9 3]


In [ ]:
print(a2)
b2 = np.delete(a2, 1, axis=0)
# 인덱스가 1인 두쨰 행을 통쨰로 날린다.
print(b2)
c2 = np.delete(a2, 1, axis=1)
print(c2)

[[1 0]
 [1 0]]
[[1 0]]
[[1]
 [1]]


### 배열 복사

* 리스트 자료형과 달리 배열의 슬라이스는 복사본이 아님

In [ ]:
print(a2)
print(a2[:1, :1])
a2_sub = a2[:1, :1]
print(a2_sub)
print(a2)

[[1 0]
 [1 0]]
[[1]]
[[1]]
[[1 0]
 [1 0]]



* `copy()`: 배열이나 하위 배열 내의 값을 명시적으로 복사

In [ ]:
print(a2)
a2_sub_copy = a2[:2, :2].copy()
print(a2_sub_copy)
a2_sub_copy[:, 1] = 1
print(a2_sub_copy)
print(a2)

[[1 0]
 [1 0]]
[[1 0]
 [1 0]]
[[1 1]
 [1 1]]
[[1 0]
 [1 0]]




---



## 배열 변환

### 배열 전치 및 축 변경

In [ ]:
print(a2)
print(a2.T)
# 배열의 데이터가 시계방향으로 돈다.

[[1 0]
 [1 0]]
[[1 1]
 [0 0]]


In [ ]:
print(a3)
print(a3.T)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 1 1]
  [4 4 4]
  [7 7 7]]

 [[2 2 2]
  [5 5 5]
  [8 8 8]]

 [[3 3 3]
  [6 6 6]
  [9 9 9]]]


In [ ]:
print(a2)
print(a2.swapaxes(1, 0))

[[1 0]
 [1 0]]
[[1 1]
 [0 0]]


In [ ]:
print(a3)
print(a3.swapaxes(0, 1))
print(a3.swapaxes(1, 2))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]
  [7 8 9]]]
[[[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]]


### 배열 재구조화


* `reshape()`: 배열의 형상을 변경

In [ ]:
n1 = np.arange(1, 10)
print(n1)
print(n1.reshape(3, 3))
# 셰잎을 변경해서 2차원으로 변경했다.


[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


* `newaxis()`: 새로운 축 추가

In [ ]:
print(n1)
print(n1[np.newaxis, :5])
print(n1[:5, np.newaxis])
# 이렇게 새롭게 설정된 축에 따라서 2차원 배열이 재생성된다.

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


### 배열 크기 변경

* 배열 모양만 변경

In [ ]:
n2 = np.random.randint(0, 10, (2, 5))
print(n2)
n2.resize((5, 2))
print(n2)

[[9 2 9 3 1]
 [7 9 1 0 4]]
[[9 2]
 [9 3]
 [1 7]
 [9 1]
 [0 4]]


* 배열 크기 증가
* 남은 공간은 0으로 채워짐

In [ ]:
n2.resize((5, 5))
print(n2)

[[9 2 9 3 1]
 [7 9 1 0 4]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


* 배열 크기 감소
* 포함되지 않은 값은 삭제됨

In [ ]:
n2.resize((3, 3))
print(n2)
# resize를 통해서 추가가 안되면 삭제가 된다.

[[9 2 9]
 [3 1 7]
 [9 1 0]]


### 배열 추가

* `append()`: 배열의 끝에 값 추가

In [ ]:
a2 = np.arange(1, 10).reshape(3, 3)
b2 = np.arange(10, 19).reshape(3, 3)
print(a2)
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


* axis 지정이 없으면 1차원 배열 형태로 변형되어 결합

In [ ]:
c2 = np.append(a2, b2)
print(c2)
# 단순한 1차원 배열값으로 리턴된다.

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


* axis를 0으로 지정
* shape[0]을 제외한 나머지 shape은 같아야 함

In [ ]:
c2 = np.append(a2, b2, axis=0)
print(c2)
# 축이 0이면 열방향으로 더해진다.

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


* axis를 1로 지정
* shape[1]을 제외한 나머지 shape은 같아야 함

In [ ]:
c2 = np.append(a2, b2, axis=1)
print(c2)
# 축이 1이면 행방향으로 더해진다.

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


### 배열 연결

* `concatenate()`: 튜플이나 배열의 리스트를 인수로 사용해 배열 연결

In [ ]:
a1 = np.array([1, 3, 5])
b1 = np.array([2, 4, 6])
np.concatenate([a1, b1])
# 배열을 연결한다.

array([1, 3, 5, 2, 4, 6])

In [ ]:
c1 = np.array([7, 8, 9])
np.concatenate([a1, b1, c1])
# 3개가 나란하게 연결된다.

array([1, 3, 5, 2, 4, 6, 7, 8, 9])

In [ ]:
a2 = np.array([[1, 2, 3], [4, 5, 6]])
np.concatenate([a2, a2])
# 열방향으로 축이 기본 설정되어 아래로 확장된다.
np.concatenate([a2, a2], axis=1)
# 이렇게 하면 행방향으로 확장된다.

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

* `vstack()`: 수직 스택(vertical stack), 1차원으로 연결

In [ ]:
np.vstack([a2, a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

* `hstack()`: 수평 스택(horizontal stack), 2차원으로 연결

In [ ]:
np.hstack([a2, a2])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

* `dstack()`: 깊이 스택(depth stack), 3차원으로 연결

In [ ]:
np.dstack([a2, a2])

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

* `stack()`: 새로운 차원으로 연결

In [ ]:
np.stack([a2, a2])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

### 배열 분할

* `split()`: 배열 분할

In [ ]:
a1 = np.arange(0, 10)
print(a1)
b1, c1 = np.split(a1, [5])
print(b1, c1)
# 인덱스 5번을 기준으로 둘로 나눠서 이를 리턴값으로 다시 받아올 수 있다.

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4] [5 6 7 8 9]


* `vsplit()`: 수직 분할, 1차원으로 분할

In [ ]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2, c2 = np.vsplit(a2, [2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[7 8 9]]


* `hsplit()`: 수평 분할, 2차원으로 분할

In [ ]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2, c2 = np.hsplit(a2, [2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]


* `dsplit()`: 깊이 분할, 3차원으로 분할

In [ ]:
a3 = np.arange(1, 28).reshape(3, 3, 3)
print(a3)
b3, c3 = np.dsplit(a3, [2])
print(b3)
print(c3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 1  2]
  [ 4  5]
  [ 7  8]]

 [[10 11]
  [13 14]
  [16 17]]

 [[19 20]
  [22 23]
  [25 26]]]
[[[ 3]
  [ 6]
  [ 9]]

 [[12]
  [15]
  [18]]

 [[21]
  [24]
  [27]]]




---



## 배열 연산

* NumPy의 배열 연산은 벡터화(vectorized) 연산을 사용
* 일반적으로 NumPy의 범용 함수(universal functions)를 통해 구현
* 배열 요소에 대한 반복적인 계산을 효율적으로 수행

### 브로드캐스팅(Broadcasting)

In [ ]:
a1 = np.array([1, 2, 3])
print(a1)
print(a1 + 5)

a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
print(a1 + a2)

b2 = np.array([1, 2, 3]).reshape(3, 1)
print(b2)
print(a1 + b2)

[1 2 3]
[6 7 8]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


### 산술 연산(Arithmetic Operators)

In [ ]:
a1 = np.arange(1, 10)
print(a1)
print(a1+1)
print(np.add(a1, 1))
print(a1-2)
print(np.subtract(a1, 2))
print(-a1)
print(np.negative(a1))
print(a1*2)
print(np.multiply(a1, 2))
print(a1/2)
print(np.divide(a1, 2))
print(a1 // 2)
print(np.floor_divide(a1, 2))
print(a1 ** 2)
print(np.power(a1, 2))
print(a1 % 2)
print(np.mod(a1, 2))

[1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10]
[ 2  3  4  5  6  7  8  9 10]
[-1  0  1  2  3  4  5  6  7]
[-1  0  1  2  3  4  5  6  7]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[ 2  4  6  8 10 12 14 16 18]
[ 2  4  6  8 10 12 14 16 18]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0 1 1 2 2 3 3 4 4]
[0 1 1 2 2 3 3 4 4]
[ 1  4  9 16 25 36 49 64 81]
[ 1  4  9 16 25 36 49 64 81]
[1 0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0 1]


In [ ]:
a1 = np.arange(1, 10)
print(a1)
b1 = np.random.randint(1, 10, size=9)
print(b1)
print(b1 + a1)
print(a1 - b1)
print(b1 * a1)
print(a1 / b1)

[1 2 3 4 5 6 7 8 9]
[8 7 9 3 4 1 1 5 3]
[ 9  9 12  7  9  7  8 13 12]
[-7 -5 -6  1  1  5  6  3  6]
[ 8 14 27 12 20  6  7 40 27]
[0.125      0.28571429 0.33333333 1.33333333 1.25       6.
 7.         1.6        3.        ]


In [ ]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2 = np.random.randint(1, 10, size=(3, 3))
print(b2)
print(a2 + b2)
print(a2 - b2)
print(b2 * b2)
print(a2 / b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5 1]
 [6 1 4]
 [3 8 2]]
[[ 5  7  4]
 [10  6 10]
 [10 16 11]]
[[-3 -3  2]
 [-2  4  2]
 [ 4  0  7]]
[[16 25  1]
 [36  1 16]
 [ 9 64  4]]
[[0.25       0.4        3.        ]
 [0.66666667 5.         1.5       ]
 [2.33333333 1.         4.5       ]]


#### 절대값 함수(Absolute Function)

* `absolute()`, `abs()`: 내장된 절대값 함수

In [ ]:
a1 = np.random.randint(-10, 10, size=5)
print(a1)
print(abs(a1))

[ 7  2  4 -7  3]
[7 2 4 7 3]


#### 제곱/제곱근 함수

* `square`, `sqrt`: 제곱, 제곱근 함수

In [ ]:
print(a1)
print(np.square(a1))
print(np.sqrt(a1))
# 복소수는 결측값으로 나온다.

[ 7  2  4 -7  3]
[49  4 16 49  9]
[2.64575131 1.41421356 2.                nan 1.73205081]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in sqrt
  This is separate from the ipykernel package so we can avoid doing imports until


#### 지수와 로그 함수 (Exponential and Log Function)

In [ ]:
a1 = np.random.randint(1, 10, size=5)
print(a1)
print(np.exp(a1))
print(np.exp2(a1))
print(np.power(a1, 2))

[1 1 6 5 1]
[  2.71828183   2.71828183 403.42879349 148.4131591    2.71828183]
[ 2.  2. 64. 32.  2.]
[ 1  1 36 25  1]


In [ ]:
print(a1)
print(np.log(a1))
print(np.log2(a1))
print(np.log10(a1))

[1 1 6 5 1]
[0.         0.         1.79175947 1.60943791 0.        ]
[0.         0.         2.5849625  2.32192809 0.        ]
[0.         0.         0.77815125 0.69897    0.        ]


In [ ]:
t = np.linspace(0, np.pi, 3)
print(t)
print(np.sin(t))
print(np.cos(t))
print(np.tan(t))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


#### 삼각 함수(Trigonometrical Function)


In [ ]:
x = [-1, 0, 1]
print(x)
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))

[-1, 0, 1]
[-1.57079633  0.          1.57079633]
[3.14159265 1.57079633 0.        ]
[-0.78539816  0.          0.78539816]


### 집계 함수(Aggregate Functions)

#### sum(): 합 계산

In [ ]:
a2 = np.random.randint(1, 10, (3, 3))
print(a2)
print(a2.sum(), np.sum(a2))
print(a2.sum(axis=1), np.sum(a2, axis=1))
print(a2.sum(axis=0), np.sum(a2, axis=0))

[[8 1 6]
 [6 3 7]
 [2 9 5]]
47 47
[15 16 16] [15 16 16]
[16 13 18] [16 13 18]


#### cumsum(): 누적합 계산

In [ ]:
a2 = np.random.randint(1, 10, (3, 3))
print(a2)
print(a2.cumsum(), np.cumsum(a2))
print(a2.cumsum(axis=1), np.cumsum(a2, axis=1))
print(a2.cumsum(axis=0), np.cumsum(a2, axis=0))
# 가산으로 덧셈이 진행된다.

[[5 8 3]
 [8 2 2]
 [5 8 4]]
[ 5 13 16 24 26 28 33 41 45] [ 5 13 16 24 26 28 33 41 45]
[[ 5 13 16]
 [ 8 10 12]
 [ 5 13 17]] [[ 5 13 16]
 [ 8 10 12]
 [ 5 13 17]]
[[ 5  8  3]
 [13 10  5]
 [18 18  9]] [[ 5  8  3]
 [13 10  5]
 [18 18  9]]


#### diff(): 차분 계산

In [ ]:
print(a2)
print(np.diff(a2))
print(np.diff(a2, axis=0))
print(np.diff(a2, axis=1))

[[5 8 3]
 [8 2 2]
 [5 8 4]]
[[ 3 -5]
 [-6  0]
 [ 3 -4]]
[[ 3 -6 -1]
 [-3  6  2]]
[[ 3 -5]
 [-6  0]
 [ 3 -4]]


#### prod(): 곱 계산

In [ ]:
print(a2)
print(np.prod(a2))
print(np.prod(a2, axis=0))
print(np.prod(a2, axis=1))

[[5 8 3]
 [8 2 2]
 [5 8 4]]
614400
[200 128  24]
[120  32 160]


#### cumprod(): 누적곱 계산

In [ ]:
print(a2)
print(np.cumprod(a2))
print(np.cumprod(a2, axis=0))
print(np.cumprod(a2, axis=1))

[[5 8 3]
 [8 2 2]
 [5 8 4]]
[     5     40    120    960   1920   3840  19200 153600 614400]
[[  5   8   3]
 [ 40  16   6]
 [200 128  24]]
[[  5  40 120]
 [  8  16  32]
 [  5  40 160]]


#### dot()/matmul(): 점곱/행렬곱 계산

In [ ]:
print(a2)
b2 = np.ones_like(a2)
print(b2)
print(np.dot(a2, b2))
print(np.matmul(a2, b2))

[[5 8 3]
 [8 2 2]
 [5 8 4]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[16 16 16]
 [12 12 12]
 [17 17 17]]
[[16 16 16]
 [12 12 12]
 [17 17 17]]


#### tensordot(): 텐서곱 계산

In [ ]:
print(a2)
print(b2)
print(np.tensordot(a2, b2))
print(np.tensordot(a2, b2, axes=0))
print(np.tensordot(a2, b2, axes=1))

[[5 8 3]
 [8 2 2]
 [5 8 4]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
45
[[[[5 5 5]
   [5 5 5]
   [5 5 5]]

  [[8 8 8]
   [8 8 8]
   [8 8 8]]

  [[3 3 3]
   [3 3 3]
   [3 3 3]]]


 [[[8 8 8]
   [8 8 8]
   [8 8 8]]

  [[2 2 2]
   [2 2 2]
   [2 2 2]]

  [[2 2 2]
   [2 2 2]
   [2 2 2]]]


 [[[5 5 5]
   [5 5 5]
   [5 5 5]]

  [[8 8 8]
   [8 8 8]
   [8 8 8]]

  [[4 4 4]
   [4 4 4]
   [4 4 4]]]]
[[16 16 16]
 [12 12 12]
 [17 17 17]]


#### cross(): 벡터곱

In [ ]:
print(a2)
print(b2)
print(np.cross(a2, b2))

[[5 8 3]
 [8 2 2]
 [5 8 4]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[ 5 -2 -3]
 [ 0 -6  6]
 [ 4 -1 -3]]


#### inner()/outer(): 내적/외적

In [ ]:
print(a2)
print(b2)
print(np.inner(a2, b2)) # 벡터의 내적
print(np.outer(a2, b2)) # 벡터의 외적

[[5 8 3]
 [8 2 2]
 [5 8 4]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[16 16 16]
 [12 12 12]
 [17 17 17]]
[[5 5 5 5 5 5 5 5 5]
 [8 8 8 8 8 8 8 8 8]
 [3 3 3 3 3 3 3 3 3]
 [8 8 8 8 8 8 8 8 8]
 [2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2]
 [5 5 5 5 5 5 5 5 5]
 [8 8 8 8 8 8 8 8 8]
 [4 4 4 4 4 4 4 4 4]]


#### mean(): 평균 계산

In [ ]:
print(a2)
print(np.mean(a2))
print(np.mean(a2, axis=0))
print(np.mean(a2, axis=1))

[[5 8 3]
 [8 2 2]
 [5 8 4]]
5.0
[6. 6. 3.]
[5.33333333 4.         5.66666667]


#### std(): 표준 편차 계산

In [ ]:
print(a2)
print(np.std(a2))
print(np.std(a2, axis=0))
print(np.std(a2, axis=1))

[[5 8 3]
 [8 2 2]
 [5 8 4]]
2.3570226039551585
[1.41421356 2.82842712 0.81649658]
[2.05480467 2.82842712 1.69967317]


#### var(): 분산 계산

In [ ]:
print(a2)
print(np.var(a2))
print(np.var(a2, axis=0))
print(np.var(a2, axis=1))

[[5 8 3]
 [8 2 2]
 [5 8 4]]
5.555555555555555
[2.         8.         0.66666667]
[4.22222222 8.         2.88888889]


#### min(): 최소값

In [ ]:
print(a2)
print(np.min(a2))
print(np.min(a2, axis=0))
print(np.min(a2, axis=1))

[[5 8 3]
 [8 2 2]
 [5 8 4]]
2
[5 2 2]
[3 2 4]


#### max(): 최대값

In [ ]:
print(a2)
print(np.max(a2))
print(np.max(a2, axis=0))
print(np.max(a2, axis=1))

[[5 8 3]
 [8 2 2]
 [5 8 4]]
8
[8 8 4]
[8 8 8]


#### argmin(): 최소값 인덱스

In [ ]:
print(a2)
print(np.argmin(a2))
print(np.argmin(a2, axis=0))
print(np.argmin(a2, axis=1))

[[5 8 3]
 [8 2 2]
 [5 8 4]]
4
[0 1 1]
[2 1 2]


#### argmax(): 최대값 인덱스

In [ ]:
print(a2)
print(np.argmax(a2))
print(np.argmax(a2, axis=0))
print(np.argmax(a2, axis=1))

[[5 8 3]
 [8 2 2]
 [5 8 4]]
1
[1 0 2]
[1 0 1]


#### median(): 중앙값

In [ ]:
print(a2)
print(np.median(a2))
print(np.median(a2, axis=0))
print(np.median(a2, axis=1))

[[5 8 3]
 [8 2 2]
 [5 8 4]]
5.0
[5. 8. 3.]
[5. 2. 5.]


#### percentile(): 백분위 수



In [ ]:
a1 = np.array([0, 1, 2, 3])
print(a1)
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='linear'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='higher'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='lower'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='nearest'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='midpoint'))


[0 1 2 3]
[0.  0.6 1.2 1.8 2.4 3. ]
[0 1 2 2 3 3]
[0 0 1 1 2 3]
[0 1 1 2 2 3]
[0.  0.5 1.5 1.5 2.5 3. ]


#### any()

In [ ]:
a2 = np.array([[False, False, True],
               [False, True, True],
               [False, False, True]
               ])

print(a2)
print(np.any(a2))
print(np.any(a2, axis=0))
print(np.any(a2, axis=1))

[[False False  True]
 [False  True  True]
 [False False  True]]
True
[False  True  True]
[ True  True  True]


#### all()

In [ ]:
print(a2)
print(np.all(a2))
print(np.all(a2, axis=0))
print(np.all(a2, axis=1))

[[False False  True]
 [False  True  True]
 [False False  True]]
False
[False False  True]
[False False False]


### 비교 연산(Comparison Operators)


In [ ]:
a1 = np.arange(1, 10)
print(a1)
print(a1 == 5)
print(a1 != 5)
print(a1 < 5)
print(a1 <= 5)
print(a1 > 5)
print(a1 >= 5)

[1 2 3 4 5 6 7 8 9]
[False False False False  True False False False False]
[ True  True  True  True False  True  True  True  True]
[ True  True  True  True False False False False False]
[ True  True  True  True  True False False False False]
[False False False False False  True  True  True  True]
[False False False False  True  True  True  True  True]


In [ ]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
print(a2 == 5)
print(a2 != 5)
print(a2 < 5)
print(a2 <= 5)
print(a2 > 5)
print(a2 >= 5)
print(np.sum(a2))
print(np.sum(a2 == 5))
print(np.count_nonzero(a2>5))
print(np.sum(a2>5, axis=1))
print(np.sum(a2>5, axis=0))
# 다음과 같이 조건식을 통해서 원하는 숫자를 걸러낼 수 있다.
print(np.any(a2>5))
print(np.any(a2>5, axis=1))
print(np.any(a2>5, axis=0))
print(np.all(a2>5))
print(np.all(a2>5))
print(np.all(a2>5))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False False]
 [False  True False]
 [False False False]]
[[ True  True  True]
 [ True False  True]
 [ True  True  True]]
[[ True  True  True]
 [ True False False]
 [False False False]]
[[ True  True  True]
 [ True  True False]
 [False False False]]
[[False False False]
 [False False  True]
 [ True  True  True]]
[[False False False]
 [False  True  True]
 [ True  True  True]]
45
1
4
[0 1 3]
[1 1 2]
True
[False  True  True]
[ True  True  True]
False
False
False


In [ ]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
b1 = np.array([1, 2, 3, 3, 4])
print(b1)
print(np.isclose(a1, b1))
# 값이 같은 곳은 트루, 같지 않으면 false가 뜬다.

[1 2 3 4 5]
[1 2 3 3 4]
[ True  True  True False False]


In [ ]:
a1 = np.array([np.nan, 2, np.inf, 4, np.NINF])
print(a1)# 결측값, 양의 무한대, 음의 무한대
print(np.isnan(a1))
print(np.isinf(a1))
print(np.isfinite(a1)) # 유한한 것 체크

[ nan   2.  inf   4. -inf]
[ True False False False False]
[False False  True False  True]
[False  True False  True False]


#### 불리언 연산자(Boolean Operators)


In [ ]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
print((a2 > 5) & (a2 < 8)) # 2차 조건 설정이 가능, and
print(a2[(a2 > 5)&(a2 < 8)]) # 행렬 조건에 넣어서 불리언 인덱싱 가능

print((a2 > 5) | (a2 < 8)) # 2차 조건 설정이 가능, or
print(a2[(a2 > 5)|(a2 < 8)]) # 행렬 조건에 넣어서 불리언 인덱싱 가능

print((a2 > 5) ^ (a2 < 8)) # 2차 조건 설정이 가능, or의 나머지가 True
print(a2[(a2 > 5) ^ (a2 < 8)]) # 행렬 조건에 넣어서 불리언 인덱싱 가능

print(~(a2 > 5)) # 2차 조건 설정이 가능, not
print(a2[~(a2 > 5)]) # 행렬 조건에 넣어서 불리언 인덱싱 가능

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False False]
 [False False  True]
 [ True False False]]
[6 7]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[1 2 3 4 5 6 7 8 9]
[[ True  True  True]
 [ True  True False]
 [False  True  True]]
[1 2 3 4 5 8 9]
[[ True  True  True]
 [ True  True False]
 [False False False]]
[1 2 3 4 5]


### 배열 정렬

In [ ]:
a1 = np.random.randint(1, 10, size=10, dtype='uint8')
print(a1)
print(np.sort(a1))
# sort를 하면 오름차순으로 정렬해준다.
print(a1)
# 원본에는 변경이 없다.
print(np.argsort(a1))
# sort를 위한 인덱스 값을 리턴해준다.
print(a1)
# 역시 원본은 변경이 없다.
print(a1.sort())
print(a1)
# 이렇게 하면 원본에 변경이 생긴다.

[9 6 2 6 7 2 2 9 2 5]
[2 2 2 2 5 6 6 7 9 9]
[9 6 2 6 7 2 2 9 2 5]
[2 5 6 8 9 1 3 4 0 7]
[9 6 2 6 7 2 2 9 2 5]
None
[2 2 2 2 5 6 6 7 9 9]


In [ ]:
a2 = np.random.randint(1, 10, (3, 3), dtype='uint8')
print(a2)
print(np.sort(a2))
# sort를 하면 오름차순으로 정렬해준다.
print(a2)
# 원본에는 변경이 없다.
print(np.argsort(a2))
# sort를 위한 인덱스 값을 리턴해준다.
print(a2)
# 역시 원본은 변경이 없다.
print(a2.sort())
print(a2)
# 이렇게 하면 원본에 변경이 생긴다.

[[8 4 2]
 [9 7 2]
 [8 8 9]]
[[2 4 8]
 [2 7 9]
 [8 8 9]]
[[8 4 2]
 [9 7 2]
 [8 8 9]]
[[2 1 0]
 [2 1 0]
 [0 1 2]]
[[8 4 2]
 [9 7 2]
 [8 8 9]]
None
[[2 4 8]
 [2 7 9]
 [8 8 9]]


#### 부분 정렬

* `partition()`: 배열에서 k개의 작은 값을 반환

In [ ]:
a1 = np.random.randint(1, 10, size=10)
print(a1)
print(np.partition(a1, 3))
# 배열에서 가장 작은 값 3개를 뽑아서 반환하라는 의미

a2 = np.random.randint(1, 10, size=(5, 5))
print(a2)
print(np.partition(a2, 3, axis=1))
print(np.partition(a2, 3, axis=0))
# 배열에서 가장 작은 값 3개를 뽑아서 반환하라는 의미
# 2차원 배열에서도 적용이 가능함

[6 7 2 6 7 1 2 4 8 9]
[1 2 2 4 6 6 7 7 8 9]
[[9 6 6 4 5]
 [6 6 8 4 7]
 [2 5 6 7 3]
 [8 1 8 6 4]
 [7 3 1 7 6]]
[[4 5 6 6 9]
 [4 6 6 7 8]
 [2 3 5 6 7]
 [6 4 1 8 8]
 [3 1 6 7 7]]
[[6 1 1 6 4]
 [2 3 6 4 3]
 [7 5 6 4 5]
 [8 6 8 7 6]
 [9 6 8 7 7]]


## 배열 입출력


In [ ]:
a2 = np.random.randint(1, 10, size=(5, 5))
print(a2)
np.save("a", a2)
# 넘파이 배열을 저장하는 바이너리 파일 .npy파일이다.

[[5 6 5 8 8]
 [2 4 3 8 8]
 [8 5 4 9 6]
 [2 2 4 9 5]
 [2 7 5 2 4]]


In [ ]:
!ls

a.npy  sample_data


In [ ]:
b2 = np.random.randint(1, 10, size=(5, 5))
print(b2)
np.savez('ab', a2, b2)
# 복수 배열을 저장시는 savez로 저장한다. 확장자는 .npz

[[9 4 6 7 8]
 [3 9 7 3 8]
 [2 6 1 6 7]
 [6 3 4 3 9]
 [5 9 9 7 3]]


In [ ]:
npy = np.load('a.npy')
print(npy)
# 저장된 배열 불러오기가 가능하다.

[[5 6 5 8 8]
 [2 4 3 8 8]
 [8 5 4 9 6]
 [2 2 4 9 5]
 [2 7 5 2 4]]


In [ ]:
npz = np.load('ab.npz')
print(npz.files)# 파일의 갯수를 확인 가능하다.
print(npz['arr_0'])
print(npz['arr_1'])
# 딕셔너리로 접근이 가능하다.

['arr_0', 'arr_1']
[[5 6 5 8 8]
 [2 4 3 8 8]
 [8 5 4 9 6]
 [2 2 4 9 5]
 [2 7 5 2 4]]
[[9 4 6 7 8]
 [3 9 7 3 8]
 [2 6 1 6 7]
 [6 3 4 3 9]
 [5 9 9 7 3]]


In [ ]:
print(a2)
np.savetxt('a2.csv', a2, delimiter=',')
# 배열을 csv로 저장

[[5 6 5 8 8]
 [2 4 3 8 8]
 [8 5 4 9 6]
 [2 2 4 9 5]
 [2 7 5 2 4]]


In [ ]:
!ls

a2.csv	ab.npz	a.npy  sample_data


In [ ]:
!cat a2.csv
# cat명령어로 불러오기가 가능하다.

5.000000000000000000e+00,6.000000000000000000e+00,5.000000000000000000e+00,8.000000000000000000e+00,8.000000000000000000e+00
2.000000000000000000e+00,4.000000000000000000e+00,3.000000000000000000e+00,8.000000000000000000e+00,8.000000000000000000e+00
8.000000000000000000e+00,5.000000000000000000e+00,4.000000000000000000e+00,9.000000000000000000e+00,6.000000000000000000e+00
2.000000000000000000e+00,2.000000000000000000e+00,4.000000000000000000e+00,9.000000000000000000e+00,5.000000000000000000e+00
2.000000000000000000e+00,7.000000000000000000e+00,5.000000000000000000e+00,2.000000000000000000e+00,4.000000000000000000e+00


In [ ]:
csv = np.loadtxt('a2.csv', delimiter=',')
print(csv)
# 구분자를 지정해줘야 불러오고 저장하기가 가능하다.

[[5. 6. 5. 8. 8.]
 [2. 4. 3. 8. 8.]
 [8. 5. 4. 9. 6.]
 [2. 2. 4. 9. 5.]
 [2. 7. 5. 2. 4.]]


In [ ]:
print(b2)
np.savetxt('b.csv', b2, delimiter=',', fmt='%.2e', header='c1, c2, c3, c4, c5')
# 소수점 2째 자리까지 자료처리, 헤더로 열 명칭 저장

[[9 4 6 7 8]
 [3 9 7 3 8]
 [2 6 1 6 7]
 [6 3 4 3 9]
 [5 9 9 7 3]]


In [ ]:
!cat b.csv

# c1, c2, c3, c4, c5
9.00e+00,4.00e+00,6.00e+00,7.00e+00,8.00e+00
3.00e+00,9.00e+00,7.00e+00,3.00e+00,8.00e+00
2.00e+00,6.00e+00,1.00e+00,6.00e+00,7.00e+00
6.00e+00,3.00e+00,4.00e+00,3.00e+00,9.00e+00
5.00e+00,9.00e+00,9.00e+00,7.00e+00,3.00e+00


In [ ]:
csv = np.loadtxt('b.csv', delimiter=',')
print(csv)

[[9. 4. 6. 7. 8.]
 [3. 9. 7. 3. 8.]
 [2. 6. 1. 6. 7.]
 [6. 3. 4. 3. 9.]
 [5. 9. 9. 7. 3.]]




---

