In [1]:
import torch

In [2]:
a = [1.0, 2.0, 3.0]

In [3]:
a[0]

1.0

In [4]:
a[2]

3.0

In [5]:
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [6]:
a[1]

tensor(1.)

In [7]:
a[2] = 2
a

tensor([1., 1., 2.])

In [8]:
points = torch.zeros(6)
points

tensor([0., 0., 0., 0., 0., 0.])

In [9]:
points[0] = 2
points[1] = 1
points[2] = 2
points[3] = 4
points[4] = 2
points[5] = 7

In [10]:
points

tensor([2., 1., 2., 4., 2., 7.])

In [11]:
points = torch.tensor([[1, 0], [2, 1]])

In [12]:
points

tensor([[1, 0],
        [2, 1]])

In [13]:
points.shape

torch.Size([2, 2])

In [14]:
some_list = list(range(6))

In [15]:
some_list[:]

[0, 1, 2, 3, 4, 5]

In [16]:
some_list[1:4]

[1, 2, 3]

In [17]:
some_list[1:]

[1, 2, 3, 4, 5]

In [18]:
some_list[1:4:2]

[1, 3]

In [19]:
points[1:4, 1]

tensor([1])

In [20]:
points[1:4, :]

tensor([[2, 1]])

In [21]:
img_t = torch.randn(3, 5, 5)
img_t

tensor([[[-0.1554, -0.3625, -1.6193,  1.4358, -0.1120],
         [-1.4643,  1.4108,  1.4409, -0.3366, -1.1812],
         [ 1.3411,  0.1369, -0.4419, -0.0415,  0.5687],
         [-1.6723,  0.4076, -1.5008,  0.1257,  0.3284],
         [-0.4060, -0.1101, -0.1461, -0.3180,  0.1683]],

        [[-1.5791, -0.4326,  1.0832, -0.0863, -0.5212],
         [-0.1243, -0.5203,  0.3981, -0.9052, -0.8252],
         [ 2.4720,  0.6260, -0.5255,  2.0168,  1.0088],
         [-0.3059, -0.0758,  0.5007, -0.1390,  1.1389],
         [ 0.6920,  0.5468, -0.6798, -0.0390, -0.9794]],

        [[ 0.9841,  0.9288, -0.8192, -0.3874, -1.5695],
         [-1.1479,  0.4633,  1.8301, -1.8545,  0.2378],
         [ 1.4872,  0.8915,  0.1997,  0.4021, -1.0791],
         [-0.0937,  0.3267, -1.5016, -0.6994,  0.4320],
         [ 1.7675,  1.9269,  1.3499, -0.6218, -0.9838]]])

In [22]:
weights = torch.randn(3)
weights

tensor([-1.1520,  0.0725, -0.7207])

In [23]:
batch_t = torch.randn(2, 3, 5, 5)
batch_t

tensor([[[[ 0.9857, -0.7614,  0.5941, -0.8720,  0.1474],
          [-0.1309, -0.0303,  1.5221, -0.5224,  0.7178],
          [ 0.5530, -0.1119,  1.2744, -0.6342,  1.5520],
          [-1.6183, -0.6684,  0.1056, -1.6693,  0.1960],
          [-0.5958, -1.5432, -1.8044, -0.7501, -0.8205]],

         [[ 0.2486, -1.1776,  0.3748, -1.2043, -0.0410],
          [ 0.7014, -0.2012,  1.2298, -0.5176,  0.1875],
          [ 1.1055, -1.4769, -0.0292, -1.1334, -0.1070],
          [ 2.1807,  0.5759, -0.9458, -1.1906, -1.2562],
          [ 0.4261, -0.6863,  0.8711,  1.8250, -1.7039]],

         [[ 0.1030, -0.2375,  2.4720,  0.2670,  1.0871],
          [ 0.2362,  0.4059, -1.7336,  0.8691,  0.2346],
          [ 2.3396, -0.2813, -0.1937, -0.5241,  0.9665],
          [ 0.5807,  0.1559,  1.3070, -1.4458, -0.2023],
          [-0.7647,  0.6131,  1.3330, -0.2407,  0.1710]]],


        [[[-0.6315,  0.5774,  1.2925,  0.7333, -0.1471],
          [ 1.8111,  0.7721,  0.0398, -0.6678, -0.1425],
          [ 0.8842,  1.

In [24]:
img_gray_naive = img_t.mean(-3)
img_gray_naive

tensor([[-0.2501,  0.0446, -0.4518,  0.3207, -0.7342],
        [-0.9122,  0.4513,  1.2230, -1.0321, -0.5895],
        [ 1.7668,  0.5515, -0.2559,  0.7924,  0.1661],
        [-0.6906,  0.2195, -0.8339, -0.2376,  0.6331],
        [ 0.6845,  0.7879,  0.1747, -0.3263, -0.5983]])

In [25]:
batch_t_naive = batch_t.mean(-3) # RGB 채널은 뒤에서 3번째에 있으므로. 이에 대해 모든 평균
batch_t_naive

tensor([[[ 0.4458, -0.7255,  1.1470, -0.6031,  0.3978],
         [ 0.2689,  0.0581,  0.3394, -0.0570,  0.3800],
         [ 1.3327, -0.6234,  0.3505, -0.7639,  0.8039],
         [ 0.3810,  0.0211,  0.1556, -1.4352, -0.4208],
         [-0.3115, -0.5388,  0.1332,  0.2781, -0.7845]],

        [[-0.1264, -0.2970,  1.0814,  0.5803, -0.7780],
         [ 0.6128, -0.6024, -0.0429,  0.6421, -0.2885],
         [ 0.5428,  0.2561, -1.3123,  0.4770,  0.0110],
         [ 0.2103, -1.0752, -0.3919, -0.7542,  0.1196],
         [-0.0960,  0.4113, -0.2195,  0.1046,  0.2631]]])

In [26]:
img_gray_naive.shape

torch.Size([5, 5])

In [27]:
batch_t_naive.shape

torch.Size([2, 5, 5])

In [28]:
unsqueeze_weights = weights.unsqueeze(-1).unsqueeze(-1)
img_weights = (img_t * unsqueeze_weights)
batch_weights = (batch_t * unsqueeze_weights)
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
batch_weights.shape, batch_t.shape, unsqueeze_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [29]:
weights.shape

torch.Size([3])

In [30]:
unsqueeze_weights.shape

torch.Size([3, 1, 1])

In [31]:
weights_named = torch.randn(3, names=['channels'])
weights_named

/var/folders/gj/jnywjty93y99mk904fhg73br0000gn/T/ipykernel_3869/2936218150.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /Users/runner/work/pytorch/pytorch/pytorch/c10/core/TensorImpl.h:1408.)
  weights_named = torch.randn(3, names=['channels'])


tensor([-0.5639, -0.6315,  0.1974], names=('channels',))

In [32]:
img_named = img_t.refine_names(..., 'channels', 'rows', 'columns')
batch_named = batch_t.refine_names(..., 'channels', 'rows', 'columns')
#...으로 해두면 기존의 차원을 건들지 않는다.
img_named, batch_named

(tensor([[[-0.1554, -0.3625, -1.6193,  1.4358, -0.1120],
          [-1.4643,  1.4108,  1.4409, -0.3366, -1.1812],
          [ 1.3411,  0.1369, -0.4419, -0.0415,  0.5687],
          [-1.6723,  0.4076, -1.5008,  0.1257,  0.3284],
          [-0.4060, -0.1101, -0.1461, -0.3180,  0.1683]],
 
         [[-1.5791, -0.4326,  1.0832, -0.0863, -0.5212],
          [-0.1243, -0.5203,  0.3981, -0.9052, -0.8252],
          [ 2.4720,  0.6260, -0.5255,  2.0168,  1.0088],
          [-0.3059, -0.0758,  0.5007, -0.1390,  1.1389],
          [ 0.6920,  0.5468, -0.6798, -0.0390, -0.9794]],
 
         [[ 0.9841,  0.9288, -0.8192, -0.3874, -1.5695],
          [-1.1479,  0.4633,  1.8301, -1.8545,  0.2378],
          [ 1.4872,  0.8915,  0.1997,  0.4021, -1.0791],
          [-0.0937,  0.3267, -1.5016, -0.6994,  0.4320],
          [ 1.7675,  1.9269,  1.3499, -0.6218, -0.9838]]],
        names=('channels', 'rows', 'columns')),
 tensor([[[[ 0.9857, -0.7614,  0.5941, -0.8720,  0.1474],
           [-0.1309, -0.0303,  

In [33]:
weights_aligned = weights_named.align_as(img_named)
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [34]:
gray_named = (img_named * weights_aligned).sum('channels')
gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

In [35]:
gray_plain = gray_named.rename(None)
gray_plain.shape, gray_plain.names

(torch.Size([5, 5]), (None, None))

In [36]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [37]:
double_points.shape, double_points.dtype, short_points.shape, short_points.dtype

(torch.Size([10, 2]), torch.float64, torch.Size([2, 2]), torch.int16)

In [38]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

In [39]:
double_points.shape, double_points.dtype, short_points.shape, short_points.dtype

(torch.Size([10, 2]), torch.float64, torch.Size([10, 2]), torch.int16)

In [40]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

In [41]:
double_points.shape, double_points.dtype, short_points.shape, short_points.dtype

(torch.Size([10, 2]), torch.float64, torch.Size([10, 2]), torch.int16)

In [42]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [43]:
a = torch.ones(3, 2)
a_t = a.transpose(0, 1)
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [44]:
a = torch.ones(3, 2)
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [45]:
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [46]:
some_t = torch.ones(3, 4, 5)
trans_t = some_t.transpose(0, 2)
some_t.shape

torch.Size([3, 4, 5])

In [47]:
trans_t.shape

torch.Size([5, 4, 3])

In [48]:
some_t.stride()

(20, 5, 1)

In [49]:
trans_t.stride()

(1, 5, 20)

In [55]:
torch.cuda.is_available()

False